### ISSUE TITLE
All uasset files in UE5.0.3 example are not recognized even map

### ISSUE THREAD

**Issue by AzadNezamdoust** [4Players/odin-example-unreal#1]
All uasset files in UE5.0.3 example are not recognized even map.
Unreal does not show the files at all in the content browser.

**Comment by svenpaulsen** [comment]
This repository uses [LFS](https://git-lfs.github.com) (large file storage) to manage pre-compiled binaries, assets and Unreal Engine map files. Note that a standard clone of the repository might only retrieve the metadata about these files managed with LFS. In order to retrieve the actual data with LFS, please follow these steps:

1. Clone the repository (with submodules):  
   `git clone --recursive https://github.com/4Players/odin-example-unreal.git`

2. Cache the actual LFS data on your local machine:  
   `git lfs fetch`

3. Replaces the metadata in the binary files with their actual contents:  
   `git lfs checkout`
   
This info was also added to the projects README.
